### ISSUE TITLE
Integration not working with HA 2025.6

### ISSUE THREAD

**Issue by poudenes** [pveiga90/What-s-up-Docker-Updates-Monitor#5]
Hi All,

Since HA 2025.6 the integration seems broken. Only debug log i get is this:

```
2025-06-12 08:55:44.503 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry WuD for wud_getupdates
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wud_getupdates/__init__.py", line 11, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(entry, "sensor")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?
2025-06-12 08:55:47.362 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Switches - momentary for momentary
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/momentary/__init__.py", line 135, in async_setup_entry
    await hass.config_entries.async_forward_entry_setup(entry, Platform.SWITCH)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?
2025-06-12 13:39:04.101 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry WuD for wud_getupdates
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wud_getupdates/__init__.py", line 11, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(entry, "sensor")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?
```

**Comment by poudenes** [comment]
With some help of ChatGPT i solved the issue:

edit file: __init__.py

replaced:
```
hass.config_entries.async_forward_entry_setup(entry, "sensor")
```
to:
```
hass.config_entries.async_forward_entry_setups(entry, ["sensor"])
```

**Comment by vorbild2220** [comment]
Thank you, that worked for me.
For anyone curious where to find it: 
Go into Studio Code Server Application in Home Assistant (or File Editor):
 -> cumstom_components
     -> wud_getupdates
         -> __init__.py

Replace:

```python
from homeassistant.config_entries import ConfigEntry
from homeassistant.core import HomeAssistant

DOMAIN = "wud_getupdates"

async def async_setup(hass: HomeAssistant, config: dict):
    return True

async def async_setup_entry(hass: HomeAssistant, entry: ConfigEntry):
    hass.async_create_task(
        hass.config_entries.async_forward_entry_setup(entry, "sensor")
    )
    return True

async def async_unload_entry(hass: HomeAssistant, entry: ConfigEntry):
    await hass.config_entries.async_forward_entry_unload(entry, "sensor")
    return True
```

with:

```python
from homeassistant.config_entries import ConfigEntry
from homeassistant.core import HomeAssistant

DOMAIN = "wud_getupdates"

async def async_setup(hass: HomeAssistant, config: dict):
    return True

async def async_setup_entry(hass: HomeAssistant, entry: ConfigEntry):
    hass.async_create_task(
        hass.config_entries.async_forward_entry_setups(entry, ["sensor"])
    )
    return True

async def async_unload_entry(hass: HomeAssistant, entry: ConfigEntry):
    await hass.config_entries.async_forward_entry_unload(entry, ["sensor"])
    return True
```
