### PR TITLE
Update __init__.py

### LINKED ISSUE #5: Integration not working with HA 2025.6
Hi All,

Since HA 2025.6 the integration seems broken. Only debug log i get is this:

```
2025-06-12 08:55:44.503 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry WuD for wud_getupdates
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wud_getupdates/__init__.py", line 11, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(entry, "sensor")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?
2025-06-12 08:55:47.362 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Switches - momentary for momentary
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/momentary/__init__.py", line 135, in async_setup_entry
    await hass.config_entries.async_forward_entry_setup(entry, Platform.SWITCH)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?
2025-06-12 13:39:04.101 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry WuD for wud_getupdates
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wud_getupdates/__init__.py", line 11, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(entry, "sensor")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?
```

### PR DESCRIPTION
**Pull request by KoljaWindeler**
fixes https://github.com/pveiga90/What-s-up-Docker-Updates-Monitor/issues/5

### CODE REVIEW

**Comment by bcutter** [comment]
Not merged yet because... @pveiga90 are you holding it back because of your major integration rework maybe? Curious to get an update. Thanks for your great work and this helpful integration! 👍

**Review by pveiga90 — APPROVED** [review]

**Comment by pveiga90** [comment]
Thank you both, @KoljaWindeler for the help and @bcutter for the reminder.

Time hasn't been abundant on this side
