### ISSUE TITLE
Integration using deprecated method

### ISSUE THREAD

**Issue by cmerkle** [pveiga90/What-s-up-Docker-Updates-Monitor#6]
After upgrading Home Assistant to 2025.6.1, I am getting the following error with the Whatsupdocker integration. I believe the integration is using a deprecated method. 

Logger: homeassistant.config_entries
Source: config_entries.py:749
First occurred: June 22, 2025 at 11:36:51 PM (6 occurrences)
Last logged: 6:06:49 AM

Error setting up entry Whatsupdocker-Orangepi5b for wud_getupdates
Error setting up entry Whatsupdocker-PVE for wud_getupdates
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wud_getupdates/__init__.py", line 11, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(entry, "sensor")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?

**Comment by portigui** [comment]
I confirm this is happing to me as well. async_forward_entry_setup was deprecated in 2025.6 it would seem. https://developers.home-assistant.io/blog/2024/06/12/async_forward_entry_setups/#:~:text=Calling%20hass.,details%2C%20review%20this%20blog%20post.

**Comment by loryanstrant** [comment]
Also experiencing this. None of the 3 devices I've got are working now. :-/

**Comment by danielvandenberg95** [comment]
Would be fixed with https://github.com/pveiga90/What-s-up-Docker-Updates-Monitor/pull/15

**Comment by loryanstrant** [comment]
Thanks, but as this was over 6 months ago I've switched to a different system.
Thanks anyway.
